# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]

optimizer_runs = 9999999
via_ir = true
out = "build/out"
cache_path = "build/cache"
fs_permissions = [{ access = "read", path = "./"}]
